export type ColorProps = {
  //* Primary
  primary500: string;
  primary400: string;
  primary300: string;
  primary200: string;
  primary100: string;
  //* Secondary
  secondary500: string;
  secondary400: string;
  secondary300: string;
  secondary200: string;
  secondary100: string;
  //* Alert & Status
  success: string;
  info: string;
  warning: string;
  error: string;
  disabled: string;
  disabledButton: string;
  //* Greyscale
  grey900: string;
  grey800: string;
  grey700: string;
  grey600: string;
  grey500: string;
  grey400: string;
  grey300: string;
  grey200: string;
  grey100: string;
  grey50: string;
  //* Dark Colors
  dark1: string;
  dark2: string;
  dark3: string;
  //* Others
  white: string;
  black: string;
  red: string;
  pink: string;
  purple: string;
  deepPurple: string;
  indigo: string;
  blue: string;
  lightBlue: string;
  cyan: string;
  teal: string;
  green: string;
  lightGreen: string;
  lime: string;
  yellow: string;
  amber: string;
  orange: string;
  deepOrange: string;
  brown: string;
  blueGrey: string;
  //* Background
  backgroundPurple: string;
  backgroundBlue: string;
  backgroundGreen: string;
  backgroundOrange: string;
  backgroundPink: string;
  backgroundYellow: string;
  //* Transparent
  transparentPurple: string;
  transparentBlue: string;
  transparentOrange: string;
  transparentYellow: string;
  transparentRed: string;
  transparentGreen: string;
  transparentCyan: string;
};
